### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by lif314** [Zerg-Overmind/GaussianFlow#1]
Thanks for your excellent work. When will the code be released? I am more curious about the calculation of optical flow, especially in static scenes.

**Comment by Zerg-Overmind** [comment]
Hi, thanks for the interest, optical flow is from off-the-shelf optical flow algorithms such as [autoflow](https://github.com/google-research/opticalflow-autoflow) and [videoflow](https://github.com/XiaoyuShi97/VideoFlow/tree/main) and is not part of our contributions. Right now, all the variables for calculating Gaussianflow are provided, you may refer to our pseudo code and cuda repo for implementation.

**Comment by lif314** [comment]
> Hi, thanks for the interest, optical flow is from off-the-shelf optical flow algorithms such as [autoflow](https://github.com/google-research/opticalflow-autoflow) and [videoflow](https://github.com/XiaoyuShi97/VideoFlow/tree/main) and is not part of our contributions. Right now, all the variables for calculating Gaussianflow are provided, you may refer to our pseudo code and cuda repo for implementation.

Thanks for your reply! I will try it!
