### ISSUE TITLE
Complete code

### ISSUE THREAD

**Issue by vamWu** [Zerg-Overmind/GaussianFlow#11]
Thank you for your outstanding work. Do you have any plans to release the complete code in the future? Although I noticed that in the previous issue #1  it said that due to some reasons, we would not open source all the content for the time being.

Perhaps you can give some inspiration for integrating your outstanding work in Real-time Photorealistic Dynamic Scene Representation and Rendering with 4D Gaussian Splatting. The following is briefly described as 4dgs). Because I noticed that in 4dgs, it is the optical flow that has its own optical flow, such as flow_2d.
Thank you very much!

**Comment by Zerg-Overmind** [comment]
Hi, thank you for the interests. Actually the code is our readme. BTW, 4dgs didn't enable the function for calculating optical flow (please refer to this [issue](https://github.com/fudan-zvg/4d-gaussian-splatting/issues/19)).

**Comment by vamWu** [comment]
Thank you very much for your reply.
I have been carefully and carefully studying your paper and github repositories recently.

I would like to ask how the weights mentioned in your readme are calculated. The description of Equation 8 in the installation of your paper is from the morphing of Equation 1. I would like to ask if this is the weight_per_gs_pixel mentioned above . If not, can you simply tell me how to calculate to get the weights

``` python
weight_per_gs_pixel = render_t_1["weight_per_gs_pixel"]

predicted_flow_by_gs = (cov_multi + proj_2D_next[gs_per_pixel] - proj_2D[gs_per_pixel].detach() - x_mu.permute(0,2,3,1).detach()) * weights.detach()


````

**Comment by Zerg-Overmind** [comment]
Sorry for the confusing, "weight" is "weight_per_gs_pixel".

**Comment by vamWu** [comment]
Thank you so much for your reply.
