### ISSUE TITLE
size error

### ISSUE THREAD

**Issue by cdfan0627** [Zerg-Overmind/GaussianFlow#2]
Hello Thanks for your excellent work.
In the README code you provided, are proj_2D_next, proj_2D and weight_per_gs_pixel respectively proj_2D_t_2, proj_2D_t_1 and weights? If so, the following error will appear.
<img width="679" alt="image" src="https://github.com/Zerg-Overmind/GaussianFlow/assets/144821204/185237b6-14cc-440b-8488-84edb7e9cd7c">

I think it is caused by the different shape of weight_per_gs_pixel.

**Comment by Zerg-Overmind** [comment]
Hi, could you provide the size or shape of individual variable?

**Comment by cdfan0627** [comment]
The shapes of proj_2D_t_2[gs_per_pixel], proj_2D_t_1[gs_per_pixel], cov_multi, x_mu.permute(0,2,3,1) are all ([20, 270, 480, 2]), and the shape of weight_per_gs_pixel is ([20, 270, 480] )

**Comment by Zerg-Overmind** [comment]
That case, you shall run weight_per_gs_pixel.unsqueeze() to make its shape as [20, 270, 480, 1].

**Comment by cdfan0627** [comment]
Thank you.  I use weight_per_gs_pixel.unsqueeze(-1)
