### ISSUE TITLE
How to save flow map

### ISSUE THREAD

**Issue by cdfan0627** [Zerg-Overmind/GaussianFlow#3]
How to save your gaussian flow map in png.

**Comment by Zerg-Overmind** [comment]
Since the size of Gaussianflow is H×W×2, which is the same as optical flow, you can visualize flow map the same as optical flow.
You may need the function in this [file](https://github.com/google-research/opticalflow-autoflow/blob/main/colabs/OpticalFlow-Inference.ipynb) for visualization.

**Comment by cdfan0627** [comment]
Is the pre-computed optical flow in your code using forward flow or backward flow? Does it utilize an occlusion mask?
Thanks

**Comment by Zerg-Overmind** [comment]
Hi, please refer to our paper for the details. It should be forward flow: t_1 -> t_2 where t_2 = t_1 + 1
