### ISSUE TITLE
questions about two implementation details of flow prior

### ISSUE THREAD

**Issue by tb2-sy** [Zerg-Overmind/GaussianFlow#5]
Thanks for your nice work!
I have questions about two implementation details of flow prior, 
1. In the paper you mentioned two off-shelf optical estimation methods, autoflow and videoflow (ref. 46 and 51). Which one did you use for the pseudo gt?
2. For multi-view video dataset (not monocular dataset) flow supervision, is optical flow calculated from a fixed view and then from the adjacent timestamp of this view?

**Comment by Zerg-Overmind** [comment]
1. We use autoflow for 4d gen task and video flow for 4d novel view synthesis. Actually we initially intended to use autoflow for all the experiments but found that autoflow failed to capture motions on dynerf dataset (very noisy and the flow supervision is not benefitial) so we changed to videoflow, which works well. Personally, I recommend videoflow for all the experiments for its nice robustness and performance.
2. Yes, you are right!

**Comment by tb2-sy** [comment]
Thank you! I got it.
